# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-09 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_image',
            field=models.ImageField(default=1, upload_to='upload/'),
            preserve_default=False,
        ),
    ]
