# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-09 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200809_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
