# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-09 16:39
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
