# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-09 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('user', '0008_auto_20200809_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('prof_pic', models.ImageField(upload_to='profile/')),
                ('username', models.CharField(max_length=60)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
